rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_head.gemfile

gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_head.gemfile
